/*
 * EEPROM_CFG.h
 *
 * Created: 27/05/2021 09:28:15 PM
 *  Author: Mark Fayez
 */ 


#ifndef EEPROM_CFG_H_
#define EEPROM_CFG_H_

#define EEPROM_SLAVE_ADDR	0x50
#define EEPROM_EN_PIN_STAT	0
#define EEPROM_EN_BIT_LOC	3
#define EEPROM_BLOCK_SEL	0

#define EEPROM_ADDR		0b01010000 //(EEPROM_SLAVE_ADDR | (EEPROM_EN_PIN_STAT << EEPROM_EN_BIT_LOC) | EEPROM_BLOCK_SEL)

#endif /* EEPROM_CFG_H_ */